# Generated by Django 3.2.20 on 2023-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='/categories'),
        ),
    ]
