# Generated by Django 3.2.20 on 2023-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Title', models.CharField(max_length=200)),
                ('Product_Description', models.TextField()),
                ('Product_Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Product_Property', models.CharField(max_length=50)),
                ('Product_Cover_Image', models.ImageField(upload_to='products')),
                ('Image1', models.ImageField(upload_to='products')),
                ('Image2', models.ImageField(upload_to='products')),
                ('Image3', models.ImageField(upload_to='products')),
                ('Image4', models.ImageField(upload_to='products')),
            ],
        ),
    ]
