# Generated by Django 3.2.20 on 2023-07-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanager', '0001_initial'),
        ('productmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorymanager.subcategorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
