# Generated by Django 3.2.20 on 2023-07-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0002_auto_20230719_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='Product_Cover_Image',
            new_name='coverImage',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='Product_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='Product_Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='Product_Property',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='Product_Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
