# Generated by Django 3.2.20 on 2023-07-20 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productmanager', '0003_auto_20230720_2103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=200)),
                ('orderprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('paymentid', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentmethod', models.CharField(blank=True, max_length=200, null=True)),
                ('shippingid', models.CharField(blank=True, max_length=200, null=True)),
                ('orderby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanager.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQuntity', models.IntegerField(blank=True, null=True)),
                ('shipping_state', models.CharField(choices=[('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='PENDING', max_length=50)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanager.ordermodel')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productmanager.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanager.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
